### ISSUE TITLE
Active Effects do not affect attributes

### ISSUE THREAD

**Issue by esfaust** [matthewswar/foundryvtt-mutants-and-masterminds#2]
First of all, this project looks great! I will probably be playing around with it until you finish and release in on Foundry, looking forward to it!

I don't know whether this is not part of the MVP, or I'm just using attributes incorrectly, but I had trouble getting active effects to change a character's stats.

![Capture](https://user-images.githubusercontent.com/6980111/116446591-1a187980-a825-11eb-944b-f616858daaa6.PNG)

Regardless of key, change mode, or effect value, I cannot get active effects to modify a character's stats.
I took a look to see if I could solve it and make a pull request, but I'm not familiar enough with the tech stack.

**Replicating the Bug:**
1. Create a character
2. Go to their Effects tab, add a new passive effect
3. Set the details of the effect, and the effect/attribute change of the effect
4. Submit changes
5. The character's attribute will not be modified as expected

**Comment by matthewswar** [comment]
Hello @esfaust! You should actually be able to get active effects working by replacing the `@` with `data.`. In this case, you'd use `data.attributes.initiative` instead. I understand the confusion as it took me a few hours of tinkering on my end until I looked up the FoundryVTT source and found that it wants a data path instead of the `@` shortcut.

If your intent is to use the Protection effect from the system, you can do so by putting the Active Effect on the Effect item instead. Here's a screenshot of how I have it setup for Flight:
![image](https://user-images.githubusercontent.com/4342020/116449617-35788a00-a80f-11eb-9a43-d1ac32b40143.png)

The important thing in the above screenshot is that the mode _must_ be Custom. `@rank` is a bit of a magic value that should be replaced with the rank of the effect (which happens [here](https://github.com/matthewswar/foundryvtt-mutants-and-masterminds/blob/master/src/module/active-effects.ts#L17)). However, this implementation isn't flawless as setting up Active Effects for characters this way means _they can't be toggled off_, but I figured that's a low priority to for now.

I still need to setup a wiki for information like the above, but I just haven't had the time. I've taken a bit of a hiatus from this project as my tabletop group hasn't had a chance to play Mutants and Masterminds yet in addition to the fact that there's someone else working on a system that's officially backed by Green Ronin.

**Comment by esfaust** [comment]
Ah, wonderful! I thought it might be something like that, but I just couldn't quite figure it out. Yeah, I saw that I could do active effects through the Effect items, it seems like a pretty good setup. Definitely usable for my group!

Completely understandable. Who knows exactly when they'll get around to FoundryVTT, so I might occasionally make some pull requests for little tweaks :)
